### ISSUE TITLE
Importer holt nur Werte aus "Default"

### ISSUE THREAD

**Issue by flibbi2** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#66] opened 2021-05-12 19:22 UTC
Beispiel Energiemonitor:

<img width="2475" alt="2021-05-12_21-19-08" src="https://user-images.githubusercontent.com/78559647/118032559-1b3ec000-b368-11eb-8744-4cb5e6de2422.png">
<img width="2280" alt="2021-05-12_21-19-42" src="https://user-images.githubusercontent.com/78559647/118032563-1bd75680-b368-11eb-9608-2930b08094ff.png">
<img width="919" alt="2021-05-12_21-20-10" src="https://user-images.githubusercontent.com/78559647/118032565-1c6fed00-b368-11eb-87eb-174dc45d5b46.png">

**Comment by christianTF** [comment] 2021-05-13 05:50
Duplicate of #56

**Closed** 2021-05-13 19:57 UTC
Labels: enhancement important, import
